### ISSUE TITLE
[core] schema overhaul

### ISSUE THREAD

**Issue by rudolfix** [scale-vector/dlt#18]
we should overhaul the existing schema to support the following
- [x] add precision and scale to applicable types -> moved to #39 
- [x] allow to add descriptions to tables and columns
- [x] review all hints and remove/add -> postponed
- [x] allow to exclude fields and tables
- [x] allow to seal table schemas to changes are ignored -> #40 
- [x] configure unpacker: which fields are propagated to child tables, ??
- [x] configure loader: write disposition (#17 )
- [x] methods to normalize names and generate paths should be pluggable and available in the schema
- [x] return child - parent relationships from normalizer and store in schema
- [x] all filters, pref types and hints without `re:` prefix are treated as regexes ^...$ for easy specification of filters without knowledge of regexes
- [x] renames the autogenerated fields and tables: adds consistent `_dlt` prefix
